import { useEffect, useMemo, useState } from 'react';
import { localApi } from '../lib/api';
export default function ClientesLocal({onChanged}){const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[form,setForm]=useState(null),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError('');try{setRows(await localApi.clientes())}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?rows.filter(r=>[r.nombre,r.apellidos,r.telefono,r.email].some(v=>String(v||'').toLowerCase().includes(q))):rows},[rows,search]);
 function open(r){setSelected(r);setForm({nombre:r.nombre||'',apellidos:r.apellidos||'',telefono:r.telefono||'',email:r.email||'',direccion:r.direccion||'',notas:r.notas||''})}
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const updated=await localApi.updateCliente(selected.id,form);setRows(rs=>rs.map(r=>r.id===updated.id?updated:r));setSelected(updated);setForm({nombre:updated.nombre||'',apellidos:updated.apellidos||'',telefono:updated.telefono||'',email:updated.email||'',direccion:updated.direccion||'',notas:updated.notas||''});onChanged?.()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="panel"><div className="module-head"><div><h2>Clientes</h2><p className="muted">Busca, abre y edita cualquier cliente guardado localmente.</p></div><button className="primary compact" onClick={load}>Actualizar</button></div><input placeholder="Buscar por nombre, teléfono o email…" value={search} onChange={e=>setSearch(e.target.value)}/>{error&&<div className="error">{error}</div>}{loading?<p className="muted">Cargando…</p>:<div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Teléfono</th><th>Email</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{[r.nombre,r.apellidos].filter(Boolean).join(' ')||'—'}</td><td>{r.telefono||'—'}</td><td>{r.email||'—'}</td><td><button className="primary compact" onClick={()=>open(r)}>Abrir / editar</button></td></tr>)}</tbody></table>{filtered.length===0&&<p className="muted">No se encontraron clientes.</p>}</div>}{selected&&form&&<div className="panel"><div className="module-head"><h2>Ficha del cliente</h2><button className="compact" onClick={()=>setSelected(null)}>Cerrar</button></div><form className="local-form" onSubmit={save}><div className="form-grid"><label>Nombre<input name="nombre" value={form.nombre} onChange={change} required/></label><label>Apellidos<input name="apellidos" value={form.apellidos} onChange={change}/></label><label>Teléfono<input name="telefono" value={form.telefono} onChange={change}/></label><label>Email<input type="email" name="email" value={form.email} onChange={change}/></label><label>Dirección<input name="direccion" value={form.direccion} onChange={change}/></label><label>Notas<textarea name="notas" value={form.notas} onChange={change}/></label></div><button className="primary compact" disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button></form></div>}</div>}
