import { useEffect, useMemo, useState } from 'react';
import { Clock3, Play, Pause, Square, RefreshCw, AlertTriangle, Pencil, Plus } from 'lucide-react';
import { localApi } from '../lib/api';

const STORAGE_KEY='taller_time_active_v2';
const PAUSE_REASONS=['descanso','esperando_pieza','esperando_autorizacion','esperando_informacion','diagnosis','otro'];
function fmt(ms){const total=Math.max(0,Math.floor((Number(ms)||0)/1000));const h=Math.floor(total/3600);const m=Math.floor((total%3600)/60);const s=total%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function dtLocal(value){if(!value)return '';const d=new Date(value);const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)}
function readActive(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||null}catch{return null}}
function saveActive(v){if(v)localStorage.setItem(STORAGE_KEY,JSON.stringify(v));else localStorage.removeItem(STORAGE_KEY)}

export default function ControlTiemposLocal({session}){
 const isAdmin=session?.user?.rol==='administrador';
 const [active,setActive]=useState(readActive);
 const [usuarios,setUsuarios]=useState([]),[ordenes,setOrdenes]=useState([]),[records,setRecords]=useState([]);
 const [selectedMechanic,setSelectedMechanic]=useState(session?.user?.id||''),[selectedOt,setSelectedOt]=useState(''),[task,setTask]=useState(''),[pauseReason,setPauseReason]=useState(PAUSE_REASONS[1]);
 const [tick,setTick]=useState(Date.now()),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [edit,setEdit]=useState(null),[manual,setManual]=useState(null);
 async function load(){try{const [u,o]=await Promise.all([localApi.usuarios(),localApi.ordenes()]);setUsuarios(u);setOrdenes(o);const lists=await Promise.all(o.map(x=>localApi.lineasOrden(x.id)));const all=[];lists.forEach((x,i)=>(x.manoObra||[]).filter(r=>Number(r.control_tiempo)===1).forEach(r=>all.push({...r,ot:o[i]})));setRecords(all.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))))}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);useEffect(()=>{saveActive(active)},[active]);useEffect(()=>{if(!active)return;const id=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(id)},[active]);
 const activeElapsed=active?Math.max(0,tick-active.startedAt-(active.pausedMs||0)-(active.pausedAt?tick-active.pausedAt:0)):0;
 const today=new Date().toISOString().slice(0,10);
 const daily=useMemo(()=>{const m=new Map();records.filter(r=>String(r.inicio_tiempo||r.created_at).slice(0,10)===today).forEach(r=>{const cur=m.get(r.mecanico_id)||{effective:0,total:0,count:0};cur.effective+=Number(r.tiempo_efectivo_ms)||Math.round(Number(r.horas||0)*3600000);cur.total+=Number(r.tiempo_total_ms)||Math.round(Number(r.horas||0)*3600000);cur.count++;m.set(r.mecanico_id,cur)});return m},[records,today]);
 function start(){setError('');if(!selectedMechanic||!selectedOt||!task.trim())return setError('Selecciona mecánico, OT y tarea.');if(active)return setError('Ya existe un trabajo activo.');setActive({mechanicId:selectedMechanic,otId:selectedOt,task:task.trim(),startedAt:Date.now(),pausedAt:null,pausedMs:0,pauses:[]})}
 function pause(){if(!active||active.pausedAt)return;setActive({...active,pausedAt:Date.now(),pauseReason})}
 function resume(){if(!active?.pausedAt)return;const extra=Date.now()-active.pausedAt;setActive({...active,pausedAt:null,pausedMs:(active.pausedMs||0)+extra,pauses:[...(active.pauses||[]),{reason:active.pauseReason,inicio:active.pausedAt,fin:Date.now(),ms:extra}]})}
 async function finish(){if(!active)return;setBusy(true);setError('');const now=Date.now();const pausedMs=active.pausedAt?(active.pausedMs||0)+now-active.pausedAt:(active.pausedMs||0);const totalMs=now-active.startedAt;const effectiveMs=Math.max(0,totalMs-pausedMs);try{await localApi.addManoObra(active.otId,{descripcion:active.task,mecanico_id:active.mechanicId,horas:Number((effectiveMs/3600000).toFixed(4)),precio_hora:0,descuento:0,observaciones:`Control de tiempos · efectivo ${fmt(effectiveMs)} · pausas ${fmt(pausedMs)}`,control_tiempo:1,inicio_tiempo:new Date(active.startedAt).toISOString(),fin_tiempo:new Date(now).toISOString(),tiempo_total_ms:totalMs,tiempo_pausa_ms:pausedMs,tiempo_efectivo_ms:effectiveMs,pausas_json:JSON.stringify(active.pauses||[])});setActive(null);setTask('');await load()}catch(e){setError(`No se pudo guardar el tiempo: ${e.message}`)}finally{setBusy(false)}}
 async function saveEdit(e){e.preventDefault();if(!edit)return;setBusy(true);setError('');try{const startMs=new Date(edit.inicio).getTime();const endMs=new Date(edit.fin).getTime();if(!Number.isFinite(startMs)||!Number.isFinite(endMs)||endMs<startMs)throw new Error('Las fechas de inicio y fin no son válidas.');const totalMs=endMs-startMs;const effectiveMs=Math.max(0,Number(edit.horas)*3600000);const pausedMs=Math.max(0,totalMs-effectiveMs);await localApi.updateManoObra(edit.ot.id,edit.id,{descripcion:edit.descripcion,mecanico_id:edit.mecanico_id,horas:Number(edit.horas),precio_hora:Number(edit.precio_hora)||0,descuento:Number(edit.descuento)||0,observaciones:edit.observaciones||'',inicio_tiempo:new Date(startMs).toISOString(),fin_tiempo:new Date(endMs).toISOString(),tiempo_total_ms:totalMs,tiempo_pausa_ms:pausedMs,tiempo_efectivo_ms:effectiveMs,pausas_json:edit.pausas_json||'[]',modificado_por:session.user.nombre,admin_password:edit.admin_password});setEdit(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function saveManual(e){e.preventDefault();if(!manual)return;setBusy(true);setError('');try{const startMs=new Date(manual.inicio).getTime();const endMs=new Date(manual.fin).getTime();if(!Number.isFinite(startMs)||!Number.isFinite(endMs)||endMs<startMs)throw new Error('Las fechas de inicio y fin no son válidas.');const totalMs=endMs-startMs;const effectiveMs=Math.max(0,Number(manual.horas)*3600000);const pausedMs=Math.max(0,totalMs-effectiveMs);await localApi.addManoObra(manual.otId,{descripcion:manual.descripcion,mecanico_id:manual.mecanico_id,horas:Number(manual.horas),precio_hora:0,descuento:0,observaciones:manual.observaciones||'Registro manual introducido por administrador',control_tiempo:1,manual:1,inicio_tiempo:new Date(startMs).toISOString(),fin_tiempo:new Date(endMs).toISOString(),tiempo_total_ms:totalMs,tiempo_pausa_ms:pausedMs,tiempo_efectivo_ms:effectiveMs,modificado_por:session.user.nombre,modificado_en:new Date().toISOString(),admin_password:manual.admin_password});setManual(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function beginEdit(r){setEdit({...r,inicio:dtLocal(r.inicio_tiempo||r.created_at),fin:dtLocal(r.fin_tiempo||r.updated_at),horas:Number(r.tiempo_efectivo_ms||0)/3600000,admin_password:''})}
 const activeOt=ordenes.find(o=>o.id===active?.otId),activeUser=usuarios.find(u=>u.id===active?.mechanicId);
 return <div className="panel"><div className="module-head"><div><h2><Clock3 size={20}/> Control de tiempos</h2><p className="muted">Los registros finalizados quedan guardados en la OT. Solo el administrador puede corregirlos.</p></div><div className="actions"><button className="compact" onClick={load}><RefreshCw size={15}/> Actualizar</button>{isAdmin&&<button className="primary compact" onClick={()=>setManual({otId:selectedOt||ordenes[0]?.id||'',mecanico_id:selectedMechanic||usuarios[0]?.id||'',descripcion:'Trabajo realizado',inicio:dtLocal(new Date(Date.now()-3600000)),fin:dtLocal(new Date()),horas:1,observaciones:'',admin_password:''})}><Plus size={15}/> Añadir tiempo</button>}</div></div>
 {error&&<div className="error"><AlertTriangle size={16}/>{error}</div>}
 <div className="stats"><div className="stat"><span>Estado</span><strong>{active?'Trabajando':'Disponible'}</strong><small>{active?active.task:'Sin reloj activo'}</small></div><div className="stat"><span>Tiempo efectivo</span><strong>{fmt(activeElapsed)}</strong><small>Trabajo actual</small></div><div className="stat"><span>Trabajos hoy</span><strong>{records.filter(r=>String(r.inicio_tiempo||r.created_at).slice(0,10)===today).length}</strong><small>Registros guardados</small></div></div>
 {!active?<div className="panel"><h3>Iniciar trabajo</h3><div className="form-grid"><label>Mecánico<select value={selectedMechanic} onChange={e=>setSelectedMechanic(e.target.value)}><option value="">Seleccionar…</option>{usuarios.map(u=><option key={u.id} value={u.id}>{[u.nombre,u.apellido].filter(Boolean).join(' ')}</option>)}</select></label><label>Orden de trabajo<select value={selectedOt} onChange={e=>setSelectedOt(e.target.value)}><option value="">Seleccionar…</option>{ordenes.filter(o=>!['entregada','cancelada'].includes(o.estado)).map(o=><option key={o.id} value={o.id}>{o.numero_ot||o.id.slice(0,8)} · {o.descripcion}</option>)}</select></label><label className="wide">Tarea<input value={task} onChange={e=>setTask(e.target.value)} placeholder="Ej. Frenos delanteros"/></label></div><button className="primary" onClick={start}><Play size={17}/> Iniciar trabajo</button></div>:<div className="panel"><div className="module-head"><div><h3>{activeOt?.numero_ot||active.otId.slice(0,8)} · {activeOt?.descripcion||'OT'}</h3><p className="muted">{[activeUser?.nombre,activeUser?.apellido].filter(Boolean).join(' ')||active.mechanicId} · {active.task}</p></div><strong className="timer">{fmt(activeElapsed)}</strong></div>{!active.pausedAt?<div className="form-grid"><label>Motivo de pausa<select value={pauseReason} onChange={e=>setPauseReason(e.target.value)}>{PAUSE_REASONS.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label></div>:<div className="error">Trabajo pausado · {active.pauseReason}</div>}<div className="actions">{!active.pausedAt?<button className="compact" onClick={pause}><Pause size={16}/> Pausar</button>:<button className="primary compact" onClick={resume}><Play size={16}/> Continuar</button>}<button className="danger compact" disabled={busy} onClick={finish}><Square size={16}/> Finalizar trabajo</button></div></div>}
 <div className="panel"><div className="module-head"><h3>Resumen de hoy</h3></div><div className="table-wrap"><table><thead><tr><th>Mecánico</th><th>Trabajos</th><th>Tiempo efectivo</th><th>Tiempo total</th><th>Pausas</th></tr></thead><tbody>{usuarios.map(u=>{const d=daily.get(u.id)||{effective:0,total:0,count:0};return <tr key={u.id}><td>{[u.nombre,u.apellido].filter(Boolean).join(' ')}</td><td>{d.count}</td><td>{fmt(d.effective)}</td><td>{fmt(d.total)}</td><td>{fmt(Math.max(0,d.total-d.effective))}</td></tr>})}</tbody></table></div></div>
 <div className="panel"><h3>Registros de tiempo</h3><div className="table-wrap"><table><thead><tr><th>Inicio</th><th>Mecánico</th><th>OT</th><th>Tarea</th><th>Total</th><th>Efectivo</th><th>Acción</th></tr></thead><tbody>{records.slice(0,100).map(r=>{const u=usuarios.find(x=>x.id===r.mecanico_id);return <tr key={r.id}><td>{r.inicio_tiempo?new Date(r.inicio_tiempo).toLocaleString('es-ES'):new Date(r.created_at).toLocaleString('es-ES')}</td><td>{[u?.nombre,u?.apellido].filter(Boolean).join(' ')||'—'}</td><td>{r.ot?.numero_ot||r.orden_id.slice(0,8)}</td><td>{r.descripcion}</td><td>{fmt(r.tiempo_total_ms||Number(r.horas)*3600000)}</td><td>{fmt(r.tiempo_efectivo_ms||Number(r.horas)*3600000)}</td><td>{isAdmin&&<button className="compact" onClick={()=>beginEdit(r)}><Pencil size={14}/> Editar</button>}</td></tr>})}{!records.length&&<tr><td colSpan="7" className="muted">Todavía no hay registros de tiempo.</td></tr>}</tbody></table></div></div>
 {edit&&<div className="panel"><h3>Editar registro — {edit.ot?.numero_ot}</h3><form onSubmit={saveEdit}><div className="form-grid"><label>Tarea<input value={edit.descripcion} onChange={e=>setEdit({...edit,descripcion:e.target.value})} required/></label><label>Mecánico<select value={edit.mecanico_id||''} onChange={e=>setEdit({...edit,mecanico_id:e.target.value})}>{usuarios.map(u=><option key={u.id} value={u.id}>{u.nombre} {u.apellido||''}</option>)}</select></label><label>Inicio<input type="datetime-local" value={edit.inicio} onChange={e=>setEdit({...edit,inicio:e.target.value})} required/></label><label>Fin<input type="datetime-local" value={edit.fin} onChange={e=>setEdit({...edit,fin:e.target.value})} required/></label><label>Horas efectivas<input type="number" min="0" step="0.01" value={edit.horas} onChange={e=>setEdit({...edit,horas:e.target.value})} required/></label><label className="wide">Motivo/observaciones<textarea value={edit.observaciones||''} onChange={e=>setEdit({...edit,observaciones:e.target.value})}/></label><label className="wide">Contraseña de administrador<input type="password" value={edit.admin_password} onChange={e=>setEdit({...edit,admin_password:e.target.value})} minLength="1" required/></label></div><div className="actions"><button type="button" className="compact" onClick={()=>setEdit(null)}>Cancelar</button><button className="primary" disabled={busy}>Guardar corrección</button></div></form></div>}
 {manual&&<div className="panel"><h3>Añadir tiempo manual — solo administrador</h3><form onSubmit={saveManual}><div className="form-grid"><label>Orden de trabajo<select value={manual.otId} onChange={e=>setManual({...manual,otId:e.target.value})} required>{ordenes.map(o=><option key={o.id} value={o.id}>{o.numero_ot||o.id.slice(0,8)} · {o.descripcion}</option>)}</select></label><label>Mecánico<select value={manual.mecanico_id} onChange={e=>setManual({...manual,mecanico_id:e.target.value})} required>{usuarios.map(u=><option key={u.id} value={u.id}>{u.nombre} {u.apellido||''}</option>)}</select></label><label className="wide">Tarea<input value={manual.descripcion} onChange={e=>setManual({...manual,descripcion:e.target.value})} required/></label><label>Inicio<input type="datetime-local" value={manual.inicio} onChange={e=>setManual({...manual,inicio:e.target.value})} required/></label><label>Fin<input type="datetime-local" value={manual.fin} onChange={e=>setManual({...manual,fin:e.target.value})} required/></label><label>Horas efectivas<input type="number" min="0" step="0.01" value={manual.horas} onChange={e=>setManual({...manual,horas:e.target.value})} required/></label><label className="wide">Observaciones<input value={manual.observaciones} onChange={e=>setManual({...manual,observaciones:e.target.value})}/></label><label className="wide">Contraseña de administrador<input type="password" value={manual.admin_password} onChange={e=>setManual({...manual,admin_password:e.target.value})} required/></label></div><div className="actions"><button type="button" className="compact" onClick={()=>setManual(null)}>Cancelar</button><button className="primary" disabled={busy}>Guardar tiempo</button></div></form></div>}
 </div>;
}