import {useEffect,useState} from 'react';
import {KeyRound,Power,RefreshCw,Save,Users} from 'lucide-react';

export default function MecanicosLocal({session}){
 const [mecanicos,setMecanicos]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[pins,setPins]=useState({});
 const load=async()=>{setError('');setMessage('');try{const rows=await window.tallerDesktop?.listMechanics?.();setMecanicos(Array.isArray(rows)?rows:[])}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const savePin=async(id)=>{const pin=pins[id]||'';if(!/^\d{4,6}$/.test(pin))return setError('El PIN debe tener entre 4 y 6 dígitos.');const password=window.prompt('Introduce la contraseña actual del administrador para cambiar este PIN:');if(!password)return;setBusy(true);setError('');setMessage('');try{await window.tallerDesktop.setMechanicPin(id,pin,password);setPins(x=>({...x,[id]:''}));setMessage('PIN actualizado correctamente.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const toggle=async(m)=>{const password=window.prompt(`Contraseña del administrador para ${m.activo?'desactivar':'activar'} a ${m.nombre}:`);if(!password)return;setBusy(true);setError('');setMessage('');try{await window.tallerDesktop.setMechanicEnabled(m.id,!Boolean(m.pin_enabled),password);setMessage('Acceso actualizado.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <section className="panel"><div className="module-head"><div><h2><Users size={20}/> Mecánicos</h2><p className="muted">Gestiona los usuarios que pueden entrar al Panel Mecánico.</p></div><button className="compact" onClick={load}><RefreshCw size={16}/>Actualizar</button></div>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<div className="table-wrap"><table><thead><tr><th>Mecánico</th><th>Acceso PIN</th><th>Nuevo PIN</th><th>Acciones</th></tr></thead><tbody>{mecanicos.map(m=><tr key={m.id}><td><strong>{m.nombre} {m.apellido||''}</strong></td><td>{Number(m.pin_enabled)===1?'Activo':'Desactivado'}</td><td><input inputMode="numeric" maxLength="6" type="password" placeholder="4-6 dígitos" value={pins[m.id]||''} onChange={e=>setPins(x=>({...x,[m.id]:e.target.value.replace(/\D/g,'')}))}/></td><td><button className="compact" disabled={busy} onClick={()=>savePin(m.id)}><Save size={15}/>Guardar PIN</button>{Number(m.pin_enabled)===1?<button className="compact" disabled={busy} onClick={()=>toggle(m)}><Power size={15}/>Desactivar</button>:<button className="compact" disabled={busy} onClick={()=>toggle(m)}><Power size={15}/>Activar</button>}</td></tr>)}</tbody></table></div><div className="muted" style={{marginTop:12}}><KeyRound size={15}/> PIN iniciales: Mecánico 1 · 1111, Mecánico 2 · 2222, Mecánico 3 · 3333.</div></section>;
}