import { useEffect, useMemo, useState } from 'react';
import { localApi } from '../lib/api';

const empty = { cliente_id:'', vehiculo_id:'', numero_ot:'', fecha_entrada:'', fecha_prevista_entrega:'', fecha_entrega:'', estado:'presupuesto', prioridad:'normal', asesor_id:'', mecanico_id:'', kilometraje_entrada:'', nivel_combustible:'', llaves_entregadas:false, motivo_entrada:'', averia_comunicada:'', diagnostico:'', trabajo_solicitado:'', danos_observaciones:'', accesorios:'', descripcion:'', observaciones:'' };
const money = n => `${Number(n || 0).toFixed(2)} €`;

export default function OrdenesLocal(){
  const [rows,setRows]=useState([]),[clientes,setClientes]=useState([]),[vehiculos,setVehiculos]=useState([]),[usuarios,setUsuarios]=useState([]);
  const [search,setSearch]=useState(''),[selected,setSelected]=useState(null),[form,setForm]=useState(null),[lines,setLines]=useState({manoObra:[],piezas:[]});
  const [lineEdit,setLineEdit]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');

  async function load(){setLoading(true);setError('');try{const[o,c,v,u]=await Promise.all([localApi.ordenes(),localApi.clientes(),localApi.vehiculos(),localApi.usuarios()]);setRows(o);setClientes(c);setVehiculos(v);setUsuarios(u)}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function loadLines(id){if(!id){setLines({manoObra:[],piezas:[]});return}try{setLines(await localApi.lineasOrden(id))}catch(e){setError(e.message)}}
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>{const c=clientes.find(x=>x.id===r.cliente_id),v=vehiculos.find(x=>x.id===r.vehiculo_id);return [r.numero_ot,r.descripcion,r.estado,c?.nombre,c?.apellidos,v?.matricula,v?.marca,v?.modelo].some(x=>String(x||'').toLowerCase().includes(q))})},[rows,search,clientes,vehiculos]);
  async function open(r){setSelected(r);setForm({...empty,...r,llaves_entregadas:!!r.llaves_entregadas});setLineEdit(null);await loadLines(r.id)}
  function newOrder(){setSelected({id:null});setForm({...empty,fecha_entrada:new Date().toISOString().slice(0,16)});setLines({manoObra:[],piezas:[]});setLineEdit(null)}
  function change(e){const{name,value,type,checked}=e.target;setForm({...form,[name]:type==='checkbox'?checked:value})}
  async function save(e){e.preventDefault();setBusy(true);setError('');try{const saved=selected?.id?await localApi.updateOrden(selected.id,form):await localApi.createOrden(form);setRows(rs=>selected?.id?rs.map(r=>r.id===saved.id?saved:r):[saved,...rs]);setSelected(saved);setForm({...empty,...saved,llaves_entregadas:!!saved.llaves_entregadas});await loadLines(saved.id)}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function addLabor(){if(!selected?.id)return setError('Guarda la OT antes de añadir mano de obra.');try{await localApi.addManoObra(selected.id,{descripcion:'Nuevo trabajo',mecanico_id:form.mecanico_id||null,horas:1,precio_hora:45,descuento:0,observaciones:''});await loadLines(selected.id)}catch(e){setError(e.message)}}
  async function addPart(){if(!selected?.id)return setError('Guarda la OT antes de añadir piezas.');try{await localApi.addPieza(selected.id,{descripcion:'Nueva pieza/material',referencia:'',cantidad:1,precio_unitario:0,descuento:0,iva:21,observaciones:''});await loadLines(selected.id)}catch(e){setError(e.message)}}
  async function delLabor(id){if(!confirm('¿Eliminar esta línea de mano de obra?'))return;try{await localApi.deleteManoObra(selected.id,id);setLineEdit(null);await loadLines(selected.id)}catch(e){setError(e.message)}}
  async function delPart(id){if(!confirm('¿Eliminar esta pieza?'))return;try{await localApi.deletePieza(selected.id,id);setLineEdit(null);await loadLines(selected.id)}catch(e){setError(e.message)}}
  async function saveLabor(e){e.preventDefault();setBusy(true);try{await localApi.updateManoObra(selected.id,lineEdit.id,{descripcion:lineEdit.descripcion,mecanico_id:lineEdit.mecanico_id||null,horas:Number(lineEdit.horas)||0,precio_hora:Number(lineEdit.precio_hora)||0,descuento:Number(lineEdit.descuento)||0,observaciones:lineEdit.observaciones||''});setLineEdit(null);await loadLines(selected.id)}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function savePart(e){e.preventDefault();setBusy(true);try{await localApi.updatePieza(selected.id,lineEdit.id,{descripcion:lineEdit.descripcion,referencia:lineEdit.referencia||'',cantidad:Number(lineEdit.cantidad)||0,precio_unitario:Number(lineEdit.precio_unitario)||0,descuento:Number(lineEdit.descuento)||0,iva:Number(lineEdit.iva)||0,observaciones:lineEdit.observaciones||''});setLineEdit(null);await loadLines(selected.id)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const laborTotal=lines.manoObra.reduce((s,x)=>s+(Number(x.horas)||0)*(Number(x.precio_hora)||0)*(1-(Number(x.descuento)||0)/100),0);
  const partsNet=lines.piezas.reduce((s,x)=>s+(Number(x.cantidad)||0)*(Number(x.precio_unitario)||0)*(1-(Number(x.descuento)||0)/100),0);
  const partsVat=lines.piezas.reduce((s,x)=>s+(Number(x.cantidad)||0)*(Number(x.precio_unitario)||0)*(1-(Number(x.descuento)||0)/100)*(Number(x.iva??21)/100),0);
  const subtotal=laborTotal+partsNet,total=subtotal+partsVat;
  const available=vehiculos.filter(v=>!form?.cliente_id||v.cliente_id===form.cliente_id);

  return <div className="panel">
    <div className="module-head"><div><h2>Órdenes de trabajo</h2><p className="muted">Recepción, planificación y seguimiento de la reparación.</p></div><div><button className="primary compact" onClick={newOrder}>+ Nueva OT</button> <button className="compact" onClick={load}>Actualizar</button></div></div>
    <input placeholder="Buscar por N.º OT, cliente, matrícula, descripción o estado…" value={search} onChange={e=>setSearch(e.target.value)}/>
    {error&&<div className="error">{error}</div>}
    {loading?<p className="muted">Cargando…</p>:<div className="table-wrap"><table><thead><tr><th>N.º OT</th><th>Cliente</th><th>Vehículo</th><th>Descripción</th><th>Estado</th><th></th></tr></thead><tbody>{filtered.map(r=>{const c=clientes.find(x=>x.id===r.cliente_id),v=vehiculos.find(x=>x.id===r.vehiculo_id);return <tr key={r.id}><td>{r.numero_ot||'—'}</td><td>{[c?.nombre,c?.apellidos].filter(Boolean).join(' ')||'—'}</td><td>{v?.matricula||'—'}</td><td>{r.descripcion||'—'}</td><td>{r.estado||'presupuesto'}</td><td><button className="primary compact" onClick={()=>open(r)}>Abrir / editar</button></td></tr>})}</tbody></table>{filtered.length===0&&<p className="muted">No se encontraron órdenes.</p>}</div>}
    {form&&<div className="panel">
      <div className="module-head"><div><h2>{selected?.id?'Ficha de OT':'Nueva orden de trabajo'}</h2><p className="muted">Datos de recepción del vehículo</p></div><button className="compact" onClick={()=>{setSelected(null);setForm(null);setLines({manoObra:[],piezas:[]});setLineEdit(null)}}>Cerrar</button></div>
      <form className="local-form" onSubmit={save}>
        <h3>Recepción</h3><div className="form-grid">
          <label>Cliente<select name="cliente_id" value={form.cliente_id} onChange={e=>setForm({...form,cliente_id:e.target.value,vehiculo_id:''})} required><option value="">Seleccionar…</option>{clientes.map(c=><option key={c.id} value={c.id}>{[c.nombre,c.apellidos].filter(Boolean).join(' ')}</option>)}</select></label>
          <label>Vehículo<select name="vehiculo_id" value={form.vehiculo_id} onChange={change} required><option value="">Seleccionar…</option>{available.map(v=><option key={v.id} value={v.id}>{v.matricula} · {v.marca||''} {v.modelo||''}</option>)}</select></label>
          <label>N.º OT<input name="numero_ot" value={form.numero_ot} onChange={change}/></label>
          <label>Estado<select name="estado" value={form.estado} onChange={change}><option value="presupuesto">Presupuesto</option><option value="pendiente_autorizacion">Pendiente de autorización</option><option value="autorizada">Autorizada</option><option value="en_espera">En espera</option><option value="en_reparacion">En reparación</option><option value="terminada">Terminada</option><option value="entregada">Entregada</option><option value="cancelada">Cancelada</option></select></label>
          <label>Prioridad<select name="prioridad" value={form.prioridad} onChange={change}><option value="normal">Normal</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></label>
          <label>Fecha/hora entrada<input type="datetime-local" name="fecha_entrada" value={form.fecha_entrada||''} onChange={change}/></label><label>Entrega prevista<input type="datetime-local" name="fecha_prevista_entrega" value={form.fecha_prevista_entrega||''} onChange={change}/></label><label>Entrega real<input type="datetime-local" name="fecha_entrega" value={form.fecha_entrega||''} onChange={change}/></label><label>Kilometraje entrada<input type="number" min="0" name="kilometraje_entrada" value={form.kilometraje_entrada||''} onChange={change}/></label>
          <label>Nivel combustible<select name="nivel_combustible" value={form.nivel_combustible||''} onChange={change}><option value="">Sin indicar</option><option value="reserva">Reserva</option><option value="1/4">1/4</option><option value="1/2">1/2</option><option value="3/4">3/4</option><option value="lleno">Lleno</option></select></label><label className="check"><input type="checkbox" name="llaves_entregadas" checked={!!form.llaves_entregadas} onChange={change}/> Llaves entregadas</label>
        </div>
        <h3>Trabajo y diagnóstico</h3><div className="form-grid"><label className="wide">Motivo de entrada<textarea name="motivo_entrada" value={form.motivo_entrada||''} onChange={change}/></label><label className="wide">Avería comunicada por el cliente<textarea name="averia_comunicada" value={form.averia_comunicada||''} onChange={change}/></label><label className="wide">Trabajo solicitado<textarea name="trabajo_solicitado" value={form.trabajo_solicitado||''} onChange={change}/></label><label className="wide">Diagnóstico<textarea name="diagnostico" value={form.diagnostico||''} onChange={change}/></label><label className="wide">Daños / observaciones exteriores<textarea name="danos_observaciones" value={form.danos_observaciones||''} onChange={change}/></label><label className="wide">Accesorios dejados en el vehículo<textarea name="accesorios" value={form.accesorios||''} onChange={change}/></label><label className="wide">Descripción resumida<input name="descripcion" value={form.descripcion||''} onChange={change} required/></label><label className="wide">Observaciones internas<textarea name="observaciones" value={form.observaciones||''} onChange={change}/></label></div>
        <h3>Responsables</h3><div className="form-grid"><label>Asesor<select name="asesor_id" value={form.asesor_id||''} onChange={change}><option value="">Sin asignar</option>{usuarios.map(u=><option key={u.id} value={u.id}>{[u.nombre,u.apellido].filter(Boolean).join(' ')}</option>)}</select></label><label>Mecánico<select name="mecanico_id" value={form.mecanico_id||''} onChange={change}><option value="">Sin asignar</option>{usuarios.map(u=><option key={u.id} value={u.id}>{[u.nombre,u.apellido].filter(Boolean).join(' ')}</option>)}</select></label></div>
        <button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar OT'}</button>
      </form>
      {selected?.id&&<>
        <div className="panel"><div className="module-head"><h3>Mano de obra</h3><button className="primary compact" onClick={addLabor}>+ Añadir trabajo</button></div><div className="table-wrap"><table><thead><tr><th>Trabajo</th><th>Horas</th><th>Precio/h</th><th>Dto.</th><th>Importe</th><th></th></tr></thead><tbody>{lines.manoObra.map(x=>{const amount=(Number(x.horas)||0)*(Number(x.precio_hora)||0)*(1-(Number(x.descuento)||0)/100);return <tr key={x.id}><td>{x.descripcion}</td><td>{x.horas}</td><td>{money(x.precio_hora)}</td><td>{x.descuento}%</td><td>{money(amount)}</td><td><button className="compact" onClick={()=>setLineEdit({...x,type:'labor'})}>Editar</button> <button className="compact" onClick={()=>delLabor(x.id)}>Eliminar</button></td></tr>})}{!lines.manoObra.length&&<tr><td colSpan="6" className="muted">No hay mano de obra.</td></tr>}</tbody></table></div></div>
        <div className="panel"><div className="module-head"><h3>Piezas y materiales</h3><button className="primary compact" onClick={addPart}>+ Añadir pieza</button></div><div className="table-wrap"><table><thead><tr><th>Pieza</th><th>Ref.</th><th>Cant.</th><th>Precio</th><th>Dto.</th><th>IVA</th><th>Importe</th><th></th></tr></thead><tbody>{lines.piezas.map(x=>{const net=(Number(x.cantidad)||0)*(Number(x.precio_unitario)||0)*(1-(Number(x.descuento)||0)/100);return <tr key={x.id}><td>{x.descripcion}</td><td>{x.referencia||'—'}</td><td>{x.cantidad}</td><td>{money(x.precio_unitario)}</td><td>{x.descuento}%</td><td>{x.iva}%</td><td>{money(net)}</td><td><button className="compact" onClick={()=>setLineEdit({...x,type:'part'})}>Editar</button> <button className="compact" onClick={()=>delPart(x.id)}>Eliminar</button></td></tr>})}{!lines.piezas.length&&<tr><td colSpan="8" className="muted">No hay piezas.</td></tr>}</tbody></table></div></div>
        <div className="totals"><div>Mano de obra: <strong>{money(laborTotal)}</strong></div><div>Piezas: <strong>{money(partsNet)}</strong></div><div>IVA piezas: <strong>{money(partsVat)}</strong></div><div>Base: <strong>{money(subtotal)}</strong></div><div>Total OT: <strong>{money(total)}</strong></div></div>
        {lineEdit&&<div className="panel"><div className="module-head"><h3>{lineEdit.type==='labor'?'Editar mano de obra':'Editar pieza/material'}</h3><button className="compact" type="button" onClick={()=>setLineEdit(null)}>Cancelar</button></div>{lineEdit.type==='labor'?<form className="local-form" onSubmit={saveLabor}><div className="form-grid"><label className="wide">Trabajo<input value={lineEdit.descripcion||''} onChange={e=>setLineEdit({...lineEdit,descripcion:e.target.value})} required/></label><label>Mecánico<select value={lineEdit.mecanico_id||''} onChange={e=>setLineEdit({...lineEdit,mecanico_id:e.target.value})}><option value="">Sin asignar</option>{usuarios.map(u=><option key={u.id} value={u.id}>{[u.nombre,u.apellido].filter(Boolean).join(' ')}</option>)}</select></label><label>Horas<input type="number" min="0" step="0.01" value={lineEdit.horas??0} onChange={e=>setLineEdit({...lineEdit,horas:e.target.value})}/></label><label>Precio/hora<input type="number" min="0" step="0.01" value={lineEdit.precio_hora??0} onChange={e=>setLineEdit({...lineEdit,precio_hora:e.target.value})}/></label><label>Descuento %<input type="number" min="0" max="100" step="0.01" value={lineEdit.descuento??0} onChange={e=>setLineEdit({...lineEdit,descuento:e.target.value})}/></label><label className="wide">Observaciones<textarea value={lineEdit.observaciones||''} onChange={e=>setLineEdit({...lineEdit,observaciones:e.target.value})}/></label></div><button className="primary" disabled={busy}>Guardar trabajo</button></form>:<form className="local-form" onSubmit={savePart}><div className="form-grid"><label className="wide">Pieza/material<input value={lineEdit.descripcion||''} onChange={e=>setLineEdit({...lineEdit,descripcion:e.target.value})} required/></label><label>Referencia<input value={lineEdit.referencia||''} onChange={e=>setLineEdit({...lineEdit,referencia:e.target.value})}/></label><label>Cantidad<input type="number" min="0" step="0.01" value={lineEdit.cantidad??1} onChange={e=>setLineEdit({...lineEdit,cantidad:e.target.value})}/></label><label>Precio unitario<input type="number" min="0" step="0.01" value={lineEdit.precio_unitario??0} onChange={e=>setLineEdit({...lineEdit,precio_unitario:e.target.value})}/></label><label>Descuento %<input type="number" min="0" max="100" step="0.01" value={lineEdit.descuento??0} onChange={e=>setLineEdit({...lineEdit,descuento:e.target.value})}/></label><label>IVA %<input type="number" min="0" max="100" step="0.01" value={lineEdit.iva??21} onChange={e=>setLineEdit({...lineEdit,iva:e.target.value})}/></label><label className="wide">Observaciones<textarea value={lineEdit.observaciones||''} onChange={e=>setLineEdit({...lineEdit,observaciones:e.target.value})}/></label></div><button className="primary" disabled={busy}>Guardar pieza</button></form>}</div>}
      </>}
    </div>}
  </div>;
}
