import {useEffect,useState} from 'react';
import {Clock3,LogIn,LogOut,Pause,Play,Square} from 'lucide-react';
import {localApi} from '../lib/api';

const PIN_API=import.meta.env.VITE_MECHANIC_PIN_URL||'http://127.0.0.1:8788';
const STORAGE_KEY='taller_time_active_v2';
const fmt=ms=>{const s=Math.max(0,Math.floor((Number(ms)||0)/1000));return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||null}catch{return null}};
const write=v=>v?localStorage.setItem(STORAGE_KEY,JSON.stringify(v)):localStorage.removeItem(STORAGE_KEY);

async function pinRequest(path,options={}){if(window.tallerDesktop){if(path==='/api/mecanico/pin/users')return {__ipc:true,users:await window.tallerDesktop.listMechanics()};if(path==='/api/mecanico/pin/login'){const body=JSON.parse(options.body||'{}');return window.tallerDesktop.loginMechanic(body.id,body.pin)}}const res=await fetch(`${PIN_API}${path}`,{headers:{'Content-Type':'application/json'},...options});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||`Error ${res.status}`);return body}

export default function PanelMecanicoLocal({onExit}){
 const [usuarios,setUsuarios]=useState([]),[ordenes,setOrdenes]=useState([]),[active,setActive]=useState(read),[selected,setSelected]=useState(''),[pin,setPin]=useState(''),[user,setUser]=useState(null),[ot,setOt]=useState(''),[task,setTask]=useState(''),[error,setError]=useState(''),[tick,setTick]=useState(Date.now()),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([pinRequest('/api/mecanico/pin/users'),localApi.ordenes()]).then(([u,o])=>{const list=u.__ipc?u.users:u;setUsuarios(list.filter(x=>Number(x.pin_enabled)===1));setOrdenes(o.filter(x=>!['entregada','cancelada'].includes(x.estado))) }).catch(e=>setError(e.message))},[]);
 useEffect(()=>{write(active)},[active]);
 useEffect(()=>{if(active){const i=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(i)}},[active]);
 const elapsed=active?Math.max(0,tick-active.startedAt-(active.pausedMs||0)-(active.pausedAt?tick-active.pausedAt:0)):0;
 const myActive=active&&user&&active.mechanicId===user.id?active:null;
 const login=async()=>{setError('');if(!selected)return setError('Selecciona tu nombre.');if(!/^\d{4,6}$/.test(pin))return setError('Introduce un PIN de 4 a 6 dígitos.');setBusy(true);try{const data=await pinRequest('/api/mecanico/pin/login',{method:'POST',body:JSON.stringify({id:selected,pin})});setUser(data.user);setPin('')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const start=()=>{if(active)return setError('Ya existe un trabajo activo.');if(!ot||!task.trim())return setError('Selecciona una OT e indica la tarea.');setActive({mechanicId:user.id,otId:ot,task:task.trim(),startedAt:Date.now(),pausedAt:null,pausedMs:0,pauses:[]})};
 const pause=()=>{if(active&&!active.pausedAt)setActive({...active,pausedAt:Date.now()})};
 const resume=()=>{if(active?.pausedAt){const now=Date.now();const extra=now-active.pausedAt;setActive({...active,pausedAt:null,pausedMs:(active.pausedMs||0)+extra,pauses:[...(active.pauses||[]),{inicio:active.pausedAt,fin:now,ms:extra}]})}};
 const finish=async()=>{if(!myActive)return;setBusy(true);const now=Date.now();const pausedMs=myActive.pausedAt?(myActive.pausedMs||0)+now-myActive.pausedAt:(myActive.pausedMs||0);const totalMs=now-myActive.startedAt;const effectiveMs=Math.max(0,totalMs-pausedMs);try{await localApi.addManoObra(myActive.otId,{descripcion:myActive.task,mecanico_id:user.id,horas:Number((effectiveMs/3600000).toFixed(4)),precio_hora:0,descuento:0,observaciones:`Panel mecánico · efectivo ${fmt(effectiveMs)} · pausas ${fmt(pausedMs)}`,control_tiempo:1,inicio_tiempo:new Date(myActive.startedAt).toISOString(),fin_tiempo:new Date(now).toISOString(),tiempo_total_ms:totalMs,tiempo_pausa_ms:pausedMs,tiempo_efectivo_ms:effectiveMs,pausas_json:JSON.stringify(myActive.pauses||[])});setActive(null);setTask('');setOt('')}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(!user)return <div className="mechanic-screen"><div className="mechanic-card"><Clock3 size={42}/><h1>Panel del Mecánico</h1><p>Selecciona tu nombre e introduce tu PIN.</p><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Seleccionar mecánico…</option>{usuarios.map(u=><option key={u.id} value={u.id}>{u.nombre} {u.apellido||''}</option>)}</select><input inputMode="numeric" type="password" maxLength="6" placeholder="PIN" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy} onClick={login}><LogIn size={18}/> {busy?'Comprobando…':'Entrar'}</button>{onExit&&<button className="compact" onClick={onExit}>Volver</button>}</div></div>;
 return <div className="mechanic-screen"><div className="mechanic-shell"><header><div><h1>Panel del Mecánico</h1><p>Hola, {user.nombre} {user.apellido||''}</p></div><button className="compact" onClick={()=>{setUser(null);setSelected('');setPin('')}}><LogOut size={16}/> Salir</button></header>{error&&<div className="error">{error}</div>}{myActive?<section className="mechanic-card active"><span className="badge">{myActive.pausedAt?'PAUSADO':'TRABAJANDO'}</span><h2>{ordenes.find(o=>o.id===myActive.otId)?.numero_ot||myActive.otId.slice(0,8)}</h2><p>{ordenes.find(o=>o.id===myActive.otId)?.descripcion||'Orden de trabajo'}</p><h3>{myActive.task}</h3><div className="big-timer">{fmt(elapsed)}</div>{myActive.pausedAt?<button className="primary large" onClick={resume}><Play/> Continuar</button>:<button className="compact large" onClick={pause}><Pause/> Pausar</button>}<button className="danger large" disabled={busy} onClick={finish}><Square/> Finalizar</button></section>:<section className="mechanic-card"><h2>Nuevo trabajo</h2><select value={ot} onChange={e=>setOt(e.target.value)}><option value="">Seleccionar OT…</option>{ordenes.map(o=><option key={o.id} value={o.id}>{o.numero_ot||o.id.slice(0,8)} · {o.descripcion}</option>)}</select><input value={task} onChange={e=>setTask(e.target.value)} placeholder="Tarea a realizar"/><button className="primary large" onClick={start}><Play/> Iniciar trabajo</button></section>}</div></div>;
}
