import express from 'express';
import cors from 'cors';
import crypto from 'node:crypto';
import {query,withTransaction} from './db-sqlite.js';
const app=express();const port=Number(process.env.BUDGET_LOCAL_PORT||8788);const deviceId=process.env.DEVICE_ID||crypto.randomUUID();app.use(cors());app.use(express.json());
async function totals(id){const [m,p]=await Promise.all([query('select horas,precio_hora,descuento,iva from ot_mano_obra where orden_id=$1',[id]),query('select cantidad,precio_unitario,descuento,iva from ot_piezas where orden_id=$1',[id])]);let base=0,iva=0;for(const x of m.rows){const net=(Number(x.horas)||0)*(Number(x.precio_hora)||0)*(1-(Number(x.descuento)||0)/100);base+=net;iva+=net*(Number(x.iva??21)/100)}for(const x of p.rows){const net=(Number(x.cantidad)||0)*(Number(x.precio_unitario)||0)*(1-(Number(x.descuento)||0)/100);base+=net;iva+=net*(Number(x.iva??21)/100)}return{base:Number(base.toFixed(2)),iva:Number(iva.toFixed(2)),total:Number((base+iva).toFixed(2))}}
app.get('/api/ordenes-trabajo/:id/presupuesto',async(req,res)=>{try{const t=await totals(req.params.id);const{rows}=await query('select * from ot_presupuestos where orden_id=$1 limit 1',[req.params.id]);res.json({... (rows[0]||{}),...t})}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/ordenes-trabajo/:id/presupuesto',async(req,res)=>{const p=req.body||{};try{const t=await totals(req.params.id);const result=await withTransaction(async c=>{const{rows}=await c.query(`insert into ot_presupuestos(id,orden_id,numero_presupuesto,fecha,validez_dias,estado,base_imponible,iva,total,observaciones_cliente,observaciones_internas) values($1,$2,$3,coalesce($4,datetime('now')),$5,coalesce($6,'pendiente'),$7,$8,$9,$10,$11) on conflict(orden_id) do update set numero_presupuesto=excluded.numero_presupuesto,fecha=excluded.fecha,validez_dias=excluded.validez_dias,estado=excluded.estado,base_imponible=excluded.base_imponible,iva=excluded.iva,total=excluded.total,observaciones_cliente=excluded.observaciones_cliente,observaciones_internas=excluded.observaciones_internas,updated_at=datetime('now') returning *`,[crypto.randomUUID(),req.params.id,p.numero_presupuesto||null,p.fecha||null,Number(p.validez_dias)||15,p.estado||'pendiente',t.base,t.iva,t.total,p.observaciones_cliente||null,p.observaciones_internas||null]);const row=rows[0];await c.query('insert into sync_outbox(entity,entity_id,operation,payload,device_id) values($1,$2,$3,$4,$5)',['ot_presupuestos',row.id,'update',JSON.stringify(row),deviceId]);return row});res.json({...result,...t})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/ordenes-trabajo/:id/presupuesto/autorizacion',async(req,res)=>{const p=req.body||{};if(!['aceptado','rechazado'].includes(p.estado))return res.status(400).json({error:'La autorización debe ser aceptado o rechazado.'});try{const result=await withTransaction(async c=>{const now=new Date().toISOString();const{rows}=await c.query('update ot_presupuestos set estado=$1,autorizado_en=case when $1=\'aceptado\' then $2 else autorizado_en end,autorizado_por=case when $1=\'aceptado\' then $3 else autorizado_por end,rechazado_en=case when $1=\'rechazado\' then $2 else rechazado_en end,rechazado_por=case when $1=\'rechazado\' then $3 else rechazado_por end,updated_at=datetime(\'now\') where orden_id=$4 returning *',[p.estado,now,p.usuario_id||null,req.params.id]);if(!rows[0])throw new Error('El presupuesto todavía no existe.');if(p.estado==='aceptado')await c.query("update ordenes_trabajo set estado='autorizada',updated_at=datetime('now') where id=$1",[req.params.id]);await c.query('insert into sync_outbox(entity,entity_id,operation,payload,device_id) values($1,$2,$3,$4,$5)',['ot_presupuestos',rows[0].id,'authorization',JSON.stringify(rows[0]),deviceId]);return rows[0]});res.json(result)}catch(e){res.status(500).json({error:e.message})}});
app.listen(port,'127.0.0.1',()=>console.log(`Presupuestos local: http://127.0.0.1:${port}`));
