import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Car,ClipboardList,Users,Wrench,LogOut,LayoutDashboard,AlertTriangle} from 'lucide-react';
import {localApi} from './lib/api';
import ClientesLocal from './modules/ClientesLocal';
import VehiculosLocal from './modules/VehiculosLocal';
import './styles.css';

function Login({onLogin}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError('');try{const res=await fetch(`${import.meta.env.VITE_LOCAL_API_URL||'http://localhost:8787'}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await res.json();if(!res.ok)throw new Error(data.error||'No se pudo iniciar sesión');localStorage.setItem('taller_session',JSON.stringify(data));onLogin(data)}catch(e){setError(e.message)}finally{setBusy(false)}}return <main className="login"><div className="login-card"><div className="brand"><div className="brand-mark"><Wrench size={25}/></div><div><strong>Taller Automotriz</strong><span>Gestión local del taller</span></div></div><h1>Iniciar sesión</h1><p className="muted">El sistema funciona en la red local y no necesita Internet.</p><form onSubmit={submit}><label>Correo electrónico<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error"><AlertTriangle size={16}/>{error}</div>}<button className="primary" disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form></div></main>}
function Dashboard({session,onLogout}){const[section,setSection]=useState('dashboard');const user=session.user;const nav=[['dashboard','Dashboard',LayoutDashboard],['clientes','Clientes',Users],['vehiculos','Vehículos',Car],['ordenes','Órdenes de trabajo',ClipboardList],['mecanicos','Mecánicos',Wrench]];const content={dashboard:<><section className="stats"><div className="stat"><span>Estado</span><strong>Operativo</strong><small>Servidor local</small></div><div className="stat"><span>Usuario</span><strong>{user.nombre} {user.apellido||''}</strong><small>{user.rol}</small></div><div className="stat"><span>Internet</span><strong>No necesaria</strong><small>Modo offline</small></div></section><div className="panel"><h2>Bienvenido, {user.nombre}</h2><p className="muted">Taller Automotriz está funcionando con la base de datos local.</p></div></>,clientes:<ClientesLocal/>,vehiculos:<VehiculosLocal/>,ordenes:<div className="panel"><h2>Órdenes de trabajo</h2><p className="muted">El módulo local de órdenes se conecta a la API del taller.</p></div>,mecanicos:<div className="panel"><h2>Mecánicos</h2><p className="muted">Gestión local de mecánicos y asignaciones.</p></div>};return <div className="app"><aside><div className="brand side"><div className="brand-mark"><Wrench size={21}/></div><div><strong>Taller Automotriz</strong><span>Panel local</span></div></div><nav>{nav.map(([id,label,Icon])=><button className={section===id?'active':''} onClick={()=>setSection(id)} key={id}><Icon size={18}/>{label}</button>)}</nav><button className="logout" onClick={onLogout}><LogOut size={18}/>Cerrar sesión</button></aside><main className="content"><header><div><div className="eyebrow">TALLER AUTOMOTRIZ · LOCAL</div><h1>{nav.find(x=>x[0]===section)?.[1]}</h1></div><div className="user-chip"><span>{user.nombre} {user.apellido||''}</span><small>{user.rol}</small></div></header>{content[section]}</main></div>}
function App(){const[user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('taller_session'))}catch{return null}});useEffect(()=>{localApi.health().catch(()=>{})},[]);function logout(){localStorage.removeItem('taller_session');setUser(null)}return user?<Dashboard session={user} onLogout={logout}/>:<Login onLogin={setUser}/>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
