import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Car, ClipboardList, Users, Wrench, LogOut, LayoutDashboard, AlertTriangle } from 'lucide-react';
import { supabase } from './lib/supabase';
import './styles.css';

function Login({ onLogin }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError(''); if(!supabase){setError('Configura VITE_SUPABASE_ANON_KEY en .env.local');setBusy(false);return;} const {data,error}=await supabase.auth.signInWithPassword({email,password}); if(error)setError(error.message); else onLogin(data.user); setBusy(false);}
  return <main className="login"><div className="login-card"><div className="brand"><div className="brand-mark"><Wrench size={25}/></div><div><strong>Taller Automotriz</strong><span>Gestión del taller</span></div></div><h1>Iniciar sesión</h1><p className="muted">Accede con tu cuenta de administrador.</p><form onSubmit={submit}><label>Correo electrónico<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label>{error&&<div className="error"><AlertTriangle size={16}/>{error}</div>}<button className="primary" disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form></div></main>
}

function Dashboard({user,onLogout}){
 const [profile,setProfile]=useState(null); const [loading,setLoading]=useState(true); const [section,setSection]=useState('dashboard');
 useEffect(()=>{(async()=>{const {data}=await supabase.from('usuarios').select('nombre,apellido,rol,activo').eq('auth_user_id',user.id).maybeSingle();setProfile(data);setLoading(false)})()},[user.id]);
 const nav=[['dashboard','Dashboard',LayoutDashboard],['clientes','Clientes',Users],['vehiculos','Vehículos',Car],['ordenes','Órdenes de trabajo',ClipboardList],['mecanicos','Mecánicos',Wrench]];
 return <div className="app"><aside><div className="brand side"><div className="brand-mark"><Wrench size={21}/></div><div><strong>Taller Automotriz</strong><span>Panel de gestión</span></div></div><nav>{nav.map(([id,label,Icon])=><button className={section===id?'active':''} onClick={()=>setSection(id)} key={id}><Icon size={18}/>{label}</button>)}</nav><button className="logout" onClick={onLogout}><LogOut size={18}/>Cerrar sesión</button></aside><main className="content"><header><div><div className="eyebrow">TALLER AUTOMOTRIZ</div><h1>{nav.find(x=>x[0]===section)?.[1]||'Dashboard'}</h1></div><div className="user-chip"><span>{profile?.nombre||user.email}</span><small>{profile?.rol||'usuario'}</small></div></header>{loading?<div className="panel">Cargando perfil…</div>:profile?.rol!=='administrador'&&profile?.rol!=='encargado'?<div className="panel"><div className="error"><AlertTriangle size={18}/>Tu cuenta está autenticada pero no tiene rol administrativo en public.usuarios.</div></div>:<><section className="stats"><div className="stat"><span>Estado</span><strong>Operativo</strong><small>Conectado a Supabase</small></div><div className="stat"><span>Usuario</span><strong>{profile.nombre} {profile.apellido}</strong><small>Administrador</small></div><div className="stat"><span>Seguridad</span><strong>RLS activo</strong><small>Acceso controlado por backend</small></div></section><div className="panel"><h2>{section==='dashboard'?'Bienvenido, '+profile.nombre:nav.find(x=>x[0]===section)?.[1]}</h2><p className="muted">Módulo preparado para conectarse con las tablas y RPC existentes de Taller Automotriz.</p>{section==='ordenes'&&<button className="primary compact" onClick={()=>alert('La RPC crear_orden_trabajo está habilitada para usuarios authenticated. El formulario de creación se implementará en el siguiente módulo.')}>Nueva orden de trabajo</button>}</div></>}</main></div>
}

function App(){const [user,setUser]=useState(null); useEffect(()=>{if(!supabase)return; supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null)); return ()=>subscription.unsubscribe()},[]); if(!supabase)return <main className="login"><div className="login-card"><div className="error"><AlertTriangle/>Falta configurar Supabase. Copia .env.example a .env.local y añade la clave publicable del proyecto.</div></div></main>; return user?<Dashboard user={user} onLogout={()=>supabase.auth.signOut()}/>:<Login onLogin={setUser}/>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
